### PR TITLE
fix model generation for class hierarchies when nullSafe-array-default is enabled

### LINKED ISSUE #79: Incorrect code generation for class hierarchies with nullSafe-array-default=true
There is another issue with code generation for class hierarchies that I didn't catch in my first PR (sorry).
When enabling `nullSafe-array-default` and some base classes in the hierarchy contain arrays then the field initializers and the call to the super constructor in the derived classes won't compile.

I have another PR ready to fix this.

### PR DESCRIPTION
**Pull request by roald-di**
Fixes https://github.com/dart-ogurets/dart-openapi-maven/issues/79

### CODE REVIEW

**Comment by roald-di** [comment]
is that failing check a problem with my pr?
I tried rolling back my changes and building k8s.yaml but its also not compiling.. is there something else I need to do?

**Comment by rvowles** [comment]
sorry, don't know yet, haven't had time to check!

**Comment by rvowles** [comment]
master branch is successfully passing its integration tests, please to a `mvn clean verify` on your branch and you will be able to see the results of the failure.

**Comment by roald-di** [comment]
I think that I'm going to need some help solving this.

The build is failing because it can't find the `pub` command:

```
The post-build script did not succeed. Cannot run program "pub" (in directory "target/it/k8s_null"): error=2, No such file or directory
```

this seems to be a problem with the CI environment, but I can't figure out what the difference would be with the last successful runs.

I ran `verify` locally on my branch and there are no errors.

**Comment by rvowles** [comment]
Ok, I'll pick it up tonight my time and see how I can help!

**Comment by rvowles** [comment]
Ok! it was pretty simple in the end - Dart has expired its support for standalone commands and these verifiers were using "pub XX".

I am pushing through a PR now which will sort this out for you.

**Comment by rvowles** [comment]
For your pipeline to succeed you will need to merge master into yours or (preferably) rebase. Your pipeline should be 💰 then and I can merge it in and release it!

**Comment by roald-di** [comment]
Thank you for helping me getting this done!

**Pull request merged**
