### PR TITLE
fix request date type to be symetric

### PR DESCRIPTION
**Pull request by robertcsakany**
The  Date type not handled well on request. The Date type does not contain any time information (as in request side) so the posted format cannot contain it.

### CODE REVIEW

**Comment by rvowles** [comment]
I'm just undergoing a massive refactoring of the deserialisation and serialisation, so I'll hold onto this @robertcsakany and include it in my current branch.

**Comment by rvowles** [comment]
Robert, could you please try rebasing this on master?

**Comment by robertcsakany** [comment]
Yes, sure. I will do it the end of this day.

**Comment by robertcsakany** [comment]
I think it can be closed, because the Date handling as I see handled in a extension in common. The another commit is related some null handling extension which is a different feature. So I think this PR can be closed.

**Comment by robertcsakany** [comment]
The missing part is https://github.com/dart-ogurets/dart-openapi-maven/pull/22

**Pull request closed without merging**
